apiVersion: v1
kind: Service
metadata:
  name: health-records-backend-service
  namespace: default
spec:
  selector:
    app: health-records-backend
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
  type: NodePort