apiVersion: apps/v1
kind: Deployment
metadata:
  name: health-records-backend
  namespace: default
  labels:
    app: health-records-backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: health-records-backend
  template:
    metadata:
      labels:
        app: health-records-backend
    spec:
      containers:
      - name: backend
        image: nishantrao2005/health-records-backend:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
        env:
        - name: SPRING_DATASOURCE_URL
          value: jdbc:mysql://host.docker.internal:3306/health_records_db?createDatabaseIfNotExist=true&useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
        - name: SPRING_DATASOURCE_USERNAME
          valueFrom:
            secretKeyRef:
              name: backend-secrets
              key: db-username
        - name: SPRING_DATASOURCE_PASSWORD
          valueFrom:
            secretKeyRef:
              name: backend-secrets
              key: db-password
        - name: JWT_SECRET
          valueFrom:
            secretKeyRef:
              name: backend-secrets
              key: jwt-secret